In [1]:
!pip install numpy

    100% |████████████████████████████████| 4.7MB 259kB/s ta 0:00:011


In [2]:
import numpy as np

In [3]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
X.shape, X.size, X.ndim, X.dtype

((3, 3), 9, 2, dtype('int64'))

In [25]:
np.arange(0, 10, 2), np.array(range(0, 10, 2))

(array([0, 2, 4, 6, 8]), array([0, 2, 4, 6, 8]))

In [23]:
np.linspace(0, 10, 5, endpoint=False)

array([0., 2., 4., 6., 8.])

In [37]:
a = np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [38]:
print('rank {}'.format(a.ndim))
print('{} elements'.format(a.size))
print('dimensions {}'.format(a.shape))

rank 2
100 elements
dimensions (10, 10)


In [39]:
print('mean of rows: {}'.format(a.mean(axis=1)))
print('mean of columns: {}'.format(a.mean(axis=0)))

mean of rows: [ 5.5 15.5 25.5 35.5 45.5 55.5 65.5 75.5 85.5 95.5]
mean of columns: [46. 47. 48. 49. 50. 51. 52. 53. 54. 55.]


In [36]:
np.linspace(11, 23, 50)

array([11.        , 11.24489796, 11.48979592, 11.73469388, 11.97959184,
       12.2244898 , 12.46938776, 12.71428571, 12.95918367, 13.20408163,
       13.44897959, 13.69387755, 13.93877551, 14.18367347, 14.42857143,
       14.67346939, 14.91836735, 15.16326531, 15.40816327, 15.65306122,
       15.89795918, 16.14285714, 16.3877551 , 16.63265306, 16.87755102,
       17.12244898, 17.36734694, 17.6122449 , 17.85714286, 18.10204082,
       18.34693878, 18.59183673, 18.83673469, 19.08163265, 19.32653061,
       19.57142857, 19.81632653, 20.06122449, 20.30612245, 20.55102041,
       20.79591837, 21.04081633, 21.28571429, 21.53061224, 21.7755102 ,
       22.02040816, 22.26530612, 22.51020408, 22.75510204, 23.        ])

In [42]:
np.log(a), a.cumsum(), np.power(a, 2)

(array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
         1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
        [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
         2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227],
        [3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
         3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738],
        [3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
         3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945],
        [3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
         3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301],
        [3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
         4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456],
        [4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
         4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524],
        [4.26267988, 4.2766

In [45]:
np.array([1,2,3,4]).reshape(-1,1)

array([[1],
       [2],
       [3],
       [4]])